apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v9l4k6lyw-nodejs 
  janus-idp.io/tekton: v9l4k6lyw-nodejs
  backstage.io/kubernetes-id: v9l4k6lyw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v9l4k6lyw-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  